name: First CI

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job1 Test
        run: echo "Job1 Test"
      - name: Run Job1 Test step 2
        run: echo "Job1 Test step 2"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run Job2 Test
        run: echo "Job2 Test"
