name: First CI

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Master Job1 Test
        run: echo "Master Job1 Test"
      - name: Run Master Job1 Test step 2
        run: echo "Master Job1 Test step 2"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run Master Job2 Test
        run: echo "Master Job2 Test"
