name: Release Branch CI

on:
  push:
    branches:
      - release

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Job1 Test
        run: echo "Release Job1 Test"
      - name: Run Release Job1 Test step 2
        run: echo "Release Job1 Test step 2"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Job2 Test
        run: echo "Release Job2 Test"
